### ISSUE TITLE
LA calculating the wrong address (off by -4)

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#1]
(Copied from StarDot at https://www.stardot.org.uk/forums/viewtopic.php?p=401976#p401976 for completeness — you've already replied on there.)

If I assemble the following:

```
10 DIM code 100
20 FOR opt=0 TO 3 STEP 3
30 P%=code
40 [ OPT opt
50 ALIGN
60 .start
70 LA T0,text
80 LI A7,4
90 LB A0,0(T0)
100 ECALL
110 RET
120 :
130 EQUS "ABCD"
140 .text
150 EQUS "EFGH"
160 ]
170 NEXT
```

... then do `CALL start`, I get an `A` printed, when I would expect an `E` (i.e. T0 appears to be loaded with an address 4 lower than it should be).

I think the actual `LB A0,0(TO)` is being assembled correctly, though.

**Comment by hoglet67** [comment]
Currently the following pseudo instructions can emit either one or two instructions, depending on the value of the arguments.
- LA
- LI

I'm open to the idea of removing the optizations, and always emittimg a two of instructions. But this would make the assembler generate different code to most other RISC-V assemblers, for example GCC.

Or just doing this for LA, as it would be unusual to use LI with a label?

Do you have any thoughts Robert?

**Comment by mincebert** [comment]
(Remembering my knowledge of RISC-V is one and half days old...)

I haven't thought about LI but I think it's unlikely to use it with a label directly, although I can see people doing calculations based on the label (e.g. to work out the size of a block by subtracting one label from another).  Searching quickly, I haven't found a good explanation of what it encodes into (the cheat sheet says "Myriad"!) — is there a 'most common' size we could assume, if we didn't have a label defined yet?

With LA, though, I would have thought it was very rare to use a single instruction as it encodes to AUIPC for the top 20 bits and then ADDI for the bottom 12 bits: for it to not need the ADDI, the offset from PC would have to be an exact multiple of 2^12 (= 4096).  You could assume it needs two, if the label was undefined, and then assemble one if not (and require a third pass) — at least that would get it right in the majority of cases, I think.

If you really did want to omit the ADDI, I would think you could just use AUIPC manually.  As an aside, I'm not sure how this is supposed to operate — e.g. whether it's supposed to mask out the bottom 12 bits and shift right by 12 to work out the offset from a 32-bit pointer for you, or you have to do that yourself.  Looking at the code here https://github.com/hoglet67/BBCSDL/blob/master/src/bbasmb_riscv.c#L583 I assume you need to do it manually.

I think they made a bit of a mistake here, encoding things to different lengths implicitly.  With ARM, I think you to explicitly specify a 'long' version of a pseudo instruction and would get an error if you used the short one but needed a long.

All this said, there's clearly enough horsepower on any modern machine that's not going to make the size of programs you write in BBC BASIC's assembler to not matter doing three passes: maybe we just need to get in the habit of doing it!

**Comment by hoglet67** [comment]
I will definitely update LA to always emit two instructions.

My inclination is to leave LI as variable, for the following reasons:
- the one-instuction forms will be very common
- it would normally be used with constants, not labels
- if used with labels, it's more likely to be label expressions, e,g, table_end - table_start, which would for small tables evaluate to the one-instruction form in both passes

There are corner cases, e,g.  table_end - table_start for a large table.

Maybe there is a half-way house for LI, which is to only optimise the case where imm20=0 and not the case where imm12 = 0. Then you are unlikely to have LI rd, label change size.

Unfortunately in the assembler code expressions are completely opaque, in that I have no visibility of whether they use labels or not, and whether those labels are defined. So doing anything "smart" is not really an option.
