### ISSUE TITLE
LB doesn't support omitted immediate offset

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#2]
(Again, copied from StarDot at https://www.stardot.org.uk/forums/viewtopic.php?p=401976#p401976 to track.)

`LB A0,(T0)` (i.e. missing out the 0 immediate offset) gives an error of `imm12 constant out of range`, whereas `LB A0,0(T0)` assembles fine.

I assume it's normally OK to omit this and a 0 assumed, but is it strictly required, or is it a bug/limitation?

**Comment by hoglet67** [comment]
I've had a go at this, and it now copes with:
```
   10 val0=0
   20 val1=1
   30 P%=&20000
   40 [
   50 LB a0,(a1)
   60 LB a0,0(a1)
   70 LB a0,(0)(a1)
   80 LB a0,((0))(a1)
   90 LB a0,val0 (a1)
  100 LB a0,(val0)(a1)
  110 LB a0,1(a1)
  120 LB a0,(1)(a1)
  130 LB a0,((1))(a1)
  140 LB a0,val1 (a1)
  150 LB a0,(val1)(a1)
  160 LB a0,-1(a1)
  170 LB a0,-(1)(a1)
  180 LB a0,(-1)(a1)
  190 LB a0,-val1 (a1)
  200 LB a0,-(val1)(a1)
  210 LB a0,(-val1)(a1)
```
There will be some corner cases, like if you use a bracketted variable for the offset, and the variable name matches one of the predefined registers. But I think I'm happy with this for now.

There is also one case where a space is required:
```
LB a0,val0 (a1)
```
I don'r really understand why that is, but I'm not going to start fiddling with Richard's expression parser.

Dave
