### ISSUE TITLE
*H. in RVBASIC gives Bad command

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#3]
(From StarDot at https://www.stardot.org.uk/forums/viewtopic.php?p=401999#p401999 — here to track.)

`*H.` (i.e. short for `*HELP`) works at the PiTubeDirect RISC-V NLE `*`-prompt but it doesn't when in RVBASIC (it gives a `Bad command`, from memory — I'm not in front of the machine right now!), but `*HELP` itself does.

If I `QUIT` from RVBASIC, `*H.` works again.  (This is on MOS 3.50 with Indigo-alpha1 of PiTubeDirect; I've not tried anything else.)

**Comment by hoglet67** [comment]
I've simplified the local command parser to not accept abbreviated forms.
