### ISSUE TITLE
Using temporary filing system names on Master gives "Bad name"

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#5]
Using LOAD or SAVE with a temporary filing system (between hyphens at the start of the filename) on the Master (at least MOS 3.50) gives `Bad name`.  For example:

```
>SAVE "-ADFS-$.TEMP.RVHELLO"
Bad name
>
```

But switching filing system and saving to the file is OK:

```
>*ADFS
>SAVE "$.TEMP.RVHELLO"
>
```

It doesn't matter if ADFS is the current filing system or not to get the error.

**Comment by mincebert** [comment]
FWIW, this problem doesn't appear to affect things like `OPENOUT`.

**Comment by hoglet67** [comment]
Sorry for not responding - for some reason Github didn't notify me. I'll investigate now.

**Comment by hoglet67** [comment]
This one is quite strange.

In Richard's BBC Basic, the quotation marks around the filename are optional. If you omit them then it works.

I suspect the issue occurs when the filename passed across the tube includes the quotation marks.

I think what's happening is that when the filename includes quotation marks, MOS 3.20 is somehow imposing a length limit. You get similar errors without a Co Pro running, if the quotation marks are present:
![capture12](https://github.com/hoglet67/BBCSDL/assets/1951463/4d24d33f-6a76-4b71-af08-ec2a81738a51)

What's curious is the length limit the MOS is imposing seems to depend on the current file system. Do you have a MOS 3.50 system to try?

I can probably fix this by sanitizing the filename in my OS wrapper class.

**Comment by mincebert** [comment]
I usually use MOS 3.50 (although I have 3.20 on a MultiOS switcher) and am getting the same behaviour as you in all cases, with a 7 character limit whilst in MMFS (even though I'm saving to `"-ADFS-XX"`) and a 10 character limit whilst in ADFS (`"-ADFS-XXXXX"`).  If I use ANFS, I get the same 10 character limit but get the error `Bad path` instead of `Bad name`, so presumably it's doing some sort of sanity check in the name using the currently selected FS.  That's presumably a MOS bug of some sort?

That said, `*SAVE -ADFS-"XXXXX" 2000+1000` does work fine and, when I use quotes with something like `*SAVE "-ADFS-XXXX" 2000+1000`, I end up with a file on my ADFS drive literally called `-ADFS-XXXX`, so I think the expected behaviour here is that you can't pass over quotes, if you want to use a temporary filing system name.

I guess the solution would be to strip the quotes out in the OS wrapper, as you're suggesting!

**Comment by hoglet67** [comment]
> I guess the solution would be to strip the quotes out in the OS wrapper, as you're suggesting!

I've done than now.
