### ISSUE TITLE
Assembler: EQUD (incorrectly?) forces alignment on 4-byte boundary

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#6]
The `EQUD` assembler directive forces an alignment on a 4-byte boundary before storing the 32-bit value:

```
   10 DIM code 100
   20 P%=code
   30 [ OPT 3
   40 ALIGN
   50 EQUB 1
   60 EQUW 2
   70 EQUD 4
   80 EQUB 1
   90 EQUQ 8
  100 ]
>RUN
00010C79                      OPT 3
00010C7C                      ALIGN
00010C7C 01                   EQUB 1
00010C7D 0002                 EQUW 2
00010C80 00000004             EQUD 4
00010C84 01                   EQUB 1
00010C85 00000008             EQUQ 8
00010C89 00000000             
```

... the `EQUD 4` is stored at &10C80 rather than immediately after the `EQUW 2` 16-bit word, at &10C7F.

The same thing does not seem to affect `EQUW` nor `EQUQ`, which seem to store at the next byte, regardless of alignment.

I don't know if this is intentional but it is inconsistent with other BBC BASICs, I think.

**Comment by hoglet67** [comment]
Sorry for not responding - for some reason Github didn't notify me. I'll investigate now.

**Comment by hoglet67** [comment]
This is now fixed.
```
00010C79                      OPT 3
00010C7C                      ALIGN
00010C7C 01                   EQUB 1
00010C7D 0002                 EQUW 2
00010C7F 00000004             EQUD 4
00010C83 01                   EQUB 1
00010C84 00000008             EQUQ 8
00010C88 00000000 
```
