### ISSUE TITLE
Assmebler: Store instructions incorrectly assembled

### ISSUE THREAD

**Issue by mincebert** [hoglet67/BBCSDL#9]
I think the encoding of store instructions is broken.  For example, `SB A0,(T0)` should be (I think) 0x00a28023 but it's encoding as 0x00028523 (which is `SB zero,10(T0)`) — register 10 (A0) and the index are ending up in the wrong place and coming out as an index, or the index affects the register.  It makes no difference if there is a 0 offset outside the brackets or not.

`SH` and `SW` are similarly affected.

```
>LIST
   10 DIM code 100
   20 P%=code
   30 [ OPT 3
   40 SB A0,(T0)
   50 SB A0,0(T0)
   60 SB A0,15(T0)
   70 SW A0,(T0)
  100 ]
>RUN
00010C79                      OPT 3
00010C7C 00028523             SB A0,(T0)
===> is SB zero,10(T0)
===> should be 00A28023
00010C80 00028523             SB A0,0(T0)
===> is SB zero,10(T0)
===> should be 00A28023
00010C84 00F28523             SB A0,15(T0)
===> is SB A5,10(T0)
===> should be 00A287A3
00010C88 0002A523             SW A0,(T0)
===> is SW zero,10(T0)
===> should be 00A2A023
```

**Comment by hoglet67** [comment]
I think this is already fixed in this commit:: ad4d001af

I'll confirm this and upload a new build.

**Comment by hoglet67** [comment]
Yes, these are fixed in the [20230911 Release](https://github.com/hoglet67/BBCSDL/releases/tag/20230911), which is now available.
```
>RUN
00010C79                      OPT 3
00010C79 00A28023             SB A0,(T0)
00010C7D 00A28023             SB A0,0(T0)
00010C81 00A287A3             SB A0,15(T0)
00010C85 00A2A023             SW A0,(T0)
```
The bug was they were being incorrectly assmbled using the format for load instructions, but with the store opcode! Hence everything being in the wrong place.

**Comment by mincebert** [comment]
Thanks for confirming — I did see the other issue but thought it was about a different type of instruction rather than a bug!

As an aside, is there any way to tell the build of RVBASIC?  I've got a few copies lying about, just to check for regressions, and it's good just to make sure I'm running the correct version — at the moment, I'm checking by the size.  If not, putting something in the startup banner may be useful.

**Comment by hoglet67** [comment]
Normally I would do a bug fix as a seperate commit, but by the time I spotted it I'd already re-written the load/save code.

At the moment the only version number displayed is Richard's version number, which I'm not changing. Let me think about how best to accomate this.

**Comment by hoglet67** [comment]
The next release will include build info in the startup banner:
```
BBC BASIC for RISC-V Co Processor 1.36a
Build 20230914 30f6210
(C) Copyright R. T. Russell, 2023
>
```
